- name: Attempting to install the {{ transform }} transform for OpenHAB
  become: false
  ansible.builtin.uri:
    url: http://localhost:8080/rest/extensions/{{ transform }}/install
    method: POST
    body_format: json
    body:
      id: "{{ transform }}"
  register: response
  until: response.status == 200
  retries: 180
  delay: 10

- name: Waiting for the {{ transform }} transform installation to complete
  become: false
  ansible.builtin.uri:
    url: http://localhost:8080/rest/extensions/{{transform}}
    return_content: true
  register: response
  until: response.status == 200 and response.json | json_query("installed")
  retries: 180
  delay: 10
